# This is a basic workflow to help you get started with Actions

name: build
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
      - name: install
        run: npm ci
      - name: Build
        run: npm run build
