# This is a basic workflow to help you get started with Actions

name: test
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
      - name: 'Test'
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test:coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
